<?php

namespace App\Filament\Resources\Structures;

use Filament\Schemas\Schema;
use Filament\Schemas\Components\Section;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Grid;
use Filament\Forms\Components\Textarea;
use Filament\Tables\Filters\TernaryFilter;
use Filament\Actions\EditAction;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Tables\Columns\TextColumn;
use App\Filament\Resources\SharedRelationManagers\IdentifiersRelationManager;
use App\Filament\Resources\Structures\RelationManagers\ChargesRelationManager;
use App\Filament\Resources\SharedRelationManagers\InteractionsPassiveRelationManager;
use App\Filament\Resources\SharedRelationManagers\InteractionsActiveRelationManager;
use App\Filament\Resources\Structures\Pages\ListStructures;
use App\Filament\Resources\Structures\Pages\CreateStructure;
use App\Filament\Resources\Structures\Pages\EditStructure;
use App\Enums\IconEnums;
use Filament\Resources\Resource;
use Filament\Tables\Table;
use App\Models\Structure;
use Filament\Infolists\Components\TextEntry;
use Filament\Tables\Filters\Filter;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\HtmlString;
use Modules\CdkDepict\CdkDepict;

class StructureResource extends Resource
{
    protected static ?string $model = Structure::class;

    protected static string | \BackedEnum | null $navigationIcon = IconEnums::STRUCTURE->value;
    protected static string | \UnitEnum | null $navigationGroup = 'Data management';


    public static function form(Schema $schema): Schema
    {
        $cdk = new CdkDepict();

        return $schema
            ->components([
                Section::make('Basic information')
                    ->columns(1)
                    ->schema([
                        TextInput::make('identifier')
                            ->hint(fn (?Model $record) => $record?->parent_id ? 'Identifier is inherited from parent.' : 'Identifiers are autogenerated and cannot be changed.')
                            ->disabled()
                            ->columnSpanFull(),
                        TextInput::make('canonical_smiles')
                            ->label('SMILES')
                            ->hint('Once validated, SMILES cannot be changed.')
                            ->required()
                            ->disabledOn('edit')
                            ->validationMessages([
                                'required' => 'The SMILES is required.',
                            ])
                            // ->endsWith()
                            ->columnSpanFull(),
                            ]),
                        TextEntry::make('structure')
                            ->label('2D structure')
                            ->hiddenOn('create')
                            ->state(fn (?Structure $record) => $record?->canonical_smiles ? new HtmlString('<img src="' . $cdk->get2dStructureUrl($record?->canonical_smiles) . '" style="max-width: 100%; max-height: 100%;">') : null),
                Section::make('Computed properties (readonly)')
                    ->columnSpanFull()
                    ->columns(2)
                    ->schema([
                        TextInput::make('molecular_weight')
                            ->hint('Calculated during the SMILES canonization.')
                            ->readOnly()
                            ->disabledOn('edit')
                            ->numeric(),
                        TextInput::make('logp')
                            ->hint('Calculated during the SMILES canonization.')
                            ->readOnly()
                            ->label('LogP')
                            ->disabledOn('edit')
                            ->numeric(),
                        TextInput::make('inchikey')
                            ->label('InChIKey')
                            ->hint('Calculated during the SMILES canonization.')
                            ->readOnly()
                            ->disabledOn('edit')
                            ->columnSpanFull(),
                        TextInput::make('inchi')
                            ->label('InChI')
                            ->hint('Calculated during the SMILES canonization.')
                            ->readOnly()
                            ->disabledOn('edit')
                            ->columnSpanFull(),
                        Grid::make(3)
                            ->schema([
                                TextInput::make('charge')
                                    ->label('Charge (Q)')
                                    ->hint('Calculated during the SMILES canonization.')
                                    ->readOnly()
                                    ->disabledOn('edit')
                                    ->columnSpanFull(),
                                TextInput::make('ph_start')
                                    ->label('pH range start')
                                    ->hint('Calculated during the SMILES canonization.')
                                    ->readOnly()
                                    ->disabledOn('edit')
                                    ->columnSpanFull(),
                                TextInput::make('ph_end')
                                    ->label('pH range end')
                                    ->hint('Calculated during the SMILES canonization.')
                                    ->readOnly()
                                    ->disabledOn('edit')
                                    ->columnSpanFull(),
                            ]),
                        Textarea::make('molfile_3d')
                            ->label('3D MOLfile')
                            ->hint('3D structure of the molecule.')
                            ->disabledOn('edit')
                            ->columnSpanFull(),
                    ])
            ]);
    }

    public static function table(Table $table): Table
    {
        $t = self::getDefaultTable($table);

        return $t
            ->filters([
                ...$t->getFilters(),
                TernaryFilter::make('parent')
                    ->label('Show only parent structures?')
                    ->queries(
                        true: fn ($query) => $query->whereNull('parent_id'),
                        false: fn ($query) => $query
                    )
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getDefaultTable(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('id')
                    ->searchable(),
                TextColumn::make('identifier')
                    ->label('Identifier')
                    ->badge()
                    ->searchable(),
                TextColumn::make('name')
                    ->toggleable(isToggledHiddenByDefault: false)
                    ->label('Name'),
                TextColumn::make('canonical_smiles')
                    ->label('SMILES')
                    ->wrap()
                    ->searchable(),
                TextColumn::make('molecular_weight')
                    ->numeric()
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable(),
                TextColumn::make('logp')
                    ->numeric()
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable(),
                TextColumn::make('created_at')
                    ->since()
                    ->dateTimeTooltip()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->since()
                    ->dateTimeTooltip()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Filter::make('identifier')
                    ->schema([
                        TextInput::make('value')
                            ->label('Identifier')
                            ->hint('Minimum 3 characters')
                            ->hintColor('warning')
                            ->placeholder('Enter identifier value...'),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        if(empty($data['value']) || strlen($data['value']) < 3) {
                            return $query;
                        }

                        return $query->whereHas('identifiers', function (Builder $query) use ($data) {
                            $query->where('value', 'ILIKE', '%' . $data['value'] . '%');
                        });
                    })->label('Identifier'),
            ]);
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->withoutGlobalScopes([
                SoftDeletingScope::class,
            ]);
    }

    public static function getRelations(): array
    {
        return [
            IdentifiersRelationManager::class,
            ChargesRelationManager::class,
            InteractionsPassiveRelationManager::class,
            InteractionsActiveRelationManager::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListStructures::route('/'),
            'create' => CreateStructure::route('/create'),
            'edit' => EditStructure::route('/{record}/edit'),
        ];
    }
}
