<?php

namespace App\Filament\Resources;

use App\Filament\Resources\SharedRelationManagers;
use App\Filament\Resources\StructureResource\Pages;
use App\Filament\Resources\StructureResource\RelationManagers;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use App\Models\Structure;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class StructureResource extends Resource
{
    protected static ?string $model = Structure::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
    protected static ?string $navigationGroup = 'Data management';
    protected static ?int $navigationSort = 2;


    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Basic information')
                    ->columns(1)
                    ->schema([
                        Forms\Components\TextInput::make('identifier')
                            ->hint(fn (?Model $record) => $record?->parent_id ? 'Identifier is inherited from parent.' : 'Identifiers are autogenerated and cannot be changed.')
                            ->disabled()
                            ->columnSpanFull(),
                        Forms\Components\TextInput::make('canonical_smiles')
                            ->label('SMILES')
                            ->hint('Once validated, SMILES cannot be changed.')
                            ->required()
                            ->disabledOn('edit')
                            ->validationMessages([
                                'required' => 'The SMILES is required.',
                            ])
                            // ->endsWith()
                            ->columnSpanFull(),
                            ]),
                Forms\Components\Section::make('Computed properties (readonly)')
                    ->columns(2)
                    ->schema([
                        Forms\Components\TextInput::make('molecular_weight')
                            ->hint('Calculated during the SMILES canonization.')
                            ->readOnly()
                            ->disabledOn('edit')
                            ->numeric(),
                        Forms\Components\TextInput::make('logp')
                            ->hint('Calculated during the SMILES canonization.')
                            ->readOnly()
                            ->label('LogP')
                            ->disabledOn('edit')
                            ->numeric(),
                        Forms\Components\TextInput::make('inchikey')
                            ->label('InChIKey')
                            ->hint('Calculated during the SMILES canonization.')
                            ->readOnly()
                            ->disabledOn('edit')
                            ->columnSpanFull(),
                        Forms\Components\TextInput::make('inchi')
                            ->label('InChI')
                            ->hint('Calculated during the SMILES canonization.')
                            ->readOnly()
                            ->disabledOn('edit')
                            ->columnSpanFull(),
                        Forms\Components\Grid::make(3)
                            ->schema([
                                Forms\Components\TextInput::make('charge')
                                    ->label('Charge (Q)')
                                    ->hint('Calculated during the SMILES canonization.')
                                    ->readOnly()
                                    ->disabledOn('edit')
                                    ->columnSpanFull(),
                                Forms\Components\TextInput::make('ph_start')
                                    ->label('pH range start')
                                    ->hint('Calculated during the SMILES canonization.')
                                    ->readOnly()
                                    ->disabledOn('edit')
                                    ->columnSpanFull(),
                                Forms\Components\TextInput::make('ph_end')
                                    ->label('pH range end')
                                    ->hint('Calculated during the SMILES canonization.')
                                    ->readOnly()
                                    ->disabledOn('edit')
                                    ->columnSpanFull(),
                            ]),
                        Forms\Components\Textarea::make('molfile_3d')
                            ->label('3D MOLfile')
                            ->hint('3D structure of the molecule.')
                            ->disabledOn('edit')
                            ->columnSpanFull(),
                    ])
            ]);
    }

    public static function table(Table $table): Table
    {
        return self::getDefaultTable($table)
            ->filters([
                Tables\Filters\TernaryFilter::make('parent')
                    ->label('Show only parent structures?')
                    ->queries(
                        true: fn ($query) => $query->whereNull('parent_id'),
                        false: fn ($query) => $query
                    )
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getDefaultTable(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('identifier')
                    ->label('Identifier')
                    ->badge()
                    ->searchable(),
                Tables\Columns\TextColumn::make('nameIdentifier.value')
                    ->toggleable(isToggledHiddenByDefault: false)
                    ->label('Name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('canonical_smiles')
                    ->label('SMILES')
                    ->wrap()
                    ->searchable(),
                Tables\Columns\TextColumn::make('molecular_weight')
                    ->numeric()
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable(),
                Tables\Columns\TextColumn::make('logp')
                    ->numeric()
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ]);
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->withoutGlobalScopes([
                SoftDeletingScope::class,
            ]);
    }

    public static function getRelations(): array
    {
        return [
            SharedRelationManagers\IdentifiersRelationManager::class,
            RelationManagers\ChargesRelationManager::class,
            SharedRelationManagers\InteractionsPassiveRelationManager::class,
            SharedRelationManagers\InteractionsActiveRelationManager::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListStructures::route('/'),
            'create' => Pages\CreateStructure::route('/create'),
            'edit' => Pages\EditStructure::route('/{record}/edit'),
        ];
    }
}
